#!/opt/local/bin/ruby
# -*- coding: utf-8 -*-
# $LOAD_PATH << File.dirname(__FILE__)
require "jabberbot"
require "gtrans"
require 'yaml'

class WassrTransBot < JabberBot
  attr_accessor :mode
  @mode = ""

  def receiver msg
    self.deliver msg.from,msg.body
     return unless  msg.body =~ /(.*): (.*) (>|&gt;) #{@mode}/
    sent = $1
    message = $2

    begin
      case @mode.to_sym
      when :ja2en
        after = GTrans::trans(message,:jp,:en)
      when :en2ja
        after = GTrans::trans(message,:en,:jp)
      end
      sendmsg = "@#{sent} #{after}"

      self.deliver(msg.from, sendmsg)
      self.logging "From:#{sent} msg:#{message} ,To:#{sendmsg}"
    rescue => e
      raise @mode + e
    end
  end
end

#
#== Entry Point
#
data = YAML.load(ARGF.read)
bot = WassrTransBot.new(data['id'],data['pass'])
bot.mode = data['mode']
bot.start

